export enum errorInfo {
    TRIT_ERROR_1 = "Bạn không phải là nhà phát hành. Yêu cầu bị từ chối",
    TRIT_ERROR_2 = "Sô lượng phải lớn hơn 0",
    TRIT_ERROR_3 = "Thiếu dữ liệu nhập vào",
    TRIT_ERROR_4 = "Lỗi trích xuất thông tin người tạo",
    TRIT_ERROR_5 = "Bạn không phải nhà cung cấp bất động sản hoặc nhà đầu tư. Yêu cầu bị từ chối",
    TRIT_ERROR_6 = "Bạn không được phép thay đổi thông tin này",
    TRIT_ERROR_7 = "UUID rỗng",
    TRIT_ERROR_8 = "ID rỗng",
    TRIT_ERROR_9 = "Bất động sản đã được tạo thành mã",
    TRIT_ERROR_10 = "Bạn không đủ coin trong tài khoản",
    TRIT_ERROR_11 = "Bất động sản này chưa được tạo mã",
    TRIT_ERROR_12 = "Transfer amount muse be less than of equal amount in SellTritAdvertisingContract",
    TRIT_ERROR_13 = "Mã phải có giá trị lớn hơn 0",
    TRIT_ERROR_14 = "Số lượng mã không đủ",
    TRIT_ERROR_15 = "Mã phải có giá trị lớn hơn 0",
    TRIT_ERROR_16 = "Amount must be smaller or equal remain trit to advertising",
    TRIT_ERROR_17 = "Bạn không có mã này trong tài sản",
    TRIT_ERROR_18 = "Diện tích của bất động sản phải lớn hơn 0",
    TRIT_ERROR_19 = "Gía của bất động sản phải lớn hơn 0",
    TRIT_ERROR_20 = "Bạn chưa nhập mô tả cho bất động sản",
    TRIT_ERROR_21 = "Bạn chưa nhập địa chỉ cho bất động sản",
    TRIT_ERROR_22 = "Chỉ người bán mã này mới có thể ngừng bán nó",
    TRIT_ERROR_23 = "Bạn chưa nhập tài khoản",
    TRIT_ERROR_24 = "Bạn chưa nhập chứng minh thư",
    TRIT_ERROR_25 = "Bạn chưa nhập FirstName",
    TRIT_ERROR_26 = "Bạn chưa nhập LastName",
    TRIT_ERROR_27 = "Tài khoản không tồn tại",
    TRIT_ERROR_28 = "Number trit of seller must greater than number trit is transferred",
    TRIT_ERROR_29 = "Không thể thay đổi tài sản",
    TRIT_ERROR_30 = "Bạn không có mã này trong tài sản",
    TRIT_ERROR_31 = "Bất động sản không tồn tại",
    TRIT_ERROR_32 = "Error getting MSP identity"

}